channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=25.0.1
- pip:
  - mlflow==2.20.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.4.1.post1
  - scipy==1.11.4
name: mlflow-env
